#!/bin/bash
# bash_env_stdlib sets some useful environment variable settings that
# are good on any machine.
#
# Copyright (C) 2015-2016, Andrew Kroshko, all rights reserved.
#
# Author: Andrew Kroshko
# Maintainer: Andrew Kroshko <akroshko.public+devel@gmail.com>
# Created: Sat Jan 30, 2015
# Version: 20160716
# URL: https://github.com/akroshko/bash-stdlib
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

# set up sage if it is installed locally: http://www.sagemath.org/
SAGEINSTALLATION=
for f in "${HOME}"/sage-*; do
    [[ -d "$f" ]] || continue
    SAGEINSTALLATION="$f"
done
if [[ -n "$SAGEINSTALLATION" ]]; then
    envaddpath PATH "$SAGEINSTALLATION"
fi
export GIT_SSH_COMMAND="ssh -o \"BatchMode yes\""
