#!/bin/bash
# bash_env
# source everything in ~/.bash_env.d/
#
# Copyright (C) 2016-2019, Andrew Kroshko, all rights reserved.
#
# Author: Andrew Kroshko
# Maintainer: Andrew Kroshko <akroshko.public+devel@gmail.com>
# Created: Wed June 08, 2016
# Version: 20180918
# URL: https://github.com/akroshko/cic-groups
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

# load everything in ~/.bash_env.d
for FILE in $HOME/.bash_env.d/*; do
    # XXXX: autosourcing files might be a security risk
    source "$FILE"
done
true
