#!/bin/bash
# https://wiki.archlinux.org/index.php/feh#File_Browser_Image_Launcher
# TODO: think --keep-zoom-vp is what I want
shopt -s nullglob

[[ -z "$1" ]] && exit 1
# FULLPATH="$(pwd)"
# else
# DNAME=$(dirname "$FULLPATH")
FULLPATH=$(readlink -f "$1")

# TODO: want --keep-zoom-vp, but does not work that well
# TODO: --scroll-step Note that this option accepts negative numbers in case you need to inverse the scroll direction; see KEYS CONFIG SYNTAX to change it permanently.  Default: 20
# TODO: microstep for smaller screens than I have?
#       but I don't see it
# taking out --force-aliasing
# TODO: actually check images manually
if [[ "${HOSTNAME}" == 'akroshko-main' ]]; then
    # TODO: extremely specific to my computer
    # TODO: check for dockapps
    # the geometry
    # TODO: edit so I can start at particular filenames
    exec feh --scale-down --scroll-step 100 --sort filename --info "exiv2 \"%f\" 2>/dev/null | grep -v ': *$'" --draw-actions --action6 ";[Edit in GIMP]nohup gimp \"%f\" &" --action7 ";[Copy filename to clipboard]echo \"%f\" | xclip -selection clipboard -i" --geometry=1848x1055+1280+0 --filelist "$FULLPATH"
    # if [[ -d "$FULLPATH" ]];then

    # else
    #     exec feh --scale-down --scroll-step 100 --sort filename --info "exiv2 \"%f\" 2>/dev/null | grep -v ': *$'" --action6 ";nohup gimp \";%f\" &" --geometry=1848x1055+1280+0 "$DNAME" --start-at "$FULLPATH"
    # fi
# else
#     # XXXX: fullscreen causes issues on viewing laptop from pcmanfm, specicific to laptop for now
#     # TODO: try and "maximize", this is often what I do on other machines.... do something with this
#     if [[ -d "FULLPATH" ]]; then
#         exec feh --scale-down --scroll-step 100 --sort filename --info "exiv2 \"%f\" 2>/dev/null | grep -v ': *$'" --action6 ";nohup gimp \"%f\" &" --geometry=1280x800+0+0 "$FULLPATH"
#     else
#         exec feh --scale-down --scroll-step 100 --sort filename --info "exiv2 \"%f\" 2>/dev/null | grep -v ': *$'" --action6 ";nohup gimp \"%f\" &" --geometry=1280x800+0+0 "$DNAME" --start-at "$FULLPATH"
#     fi
fi

    # # XXXX: fullscreen causes issues on viewing laptop from pcmanfm, specicific to laptop for now
    # # TODO: try and "maximize", this is often what I do on other machines.... do something with this
    # if [[ -d "FULLPATH" ]]; then
    #     feh --keep-zoom-vp --force-aliasing --scroll-step 100 --sort filename --info "exiv2 \"%f\" 2>/dev/null | grep -v ': *$'" --action6 ";nohup gimp \"%f\" &" --geometry=1280x800+0+0 "$FULLPATH"
    # else
    #     feh --keep-zoom-vp --force-aliasing --scroll-step 100 --sort filename --info "exiv2 \"%f\" 2>/dev/null | grep -v ': *$'" --action6 ";nohup gimp \"%f\" &" --geometry=1280x800+0+0 "$DNAME" --start-at "$FULLPATH"
    # fi
