#!/bin/bash
# bash_functions_stdlib is a set of bash functions for common operations
#
# Copyright (C) 2015-2016 Andrew Kroshko, all rights reserved.
#
# Author: Andrew Kroshko
# Maintainer: Andrew Kroshko <akroshko.public+devel@gmail.com>
# Created: Sun Sep 20, 2015
# Version: 20160131
# URL: https://github.com/akroshko/bash-stdlib
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

# check if the Emacs server is running, if not start the server
# see http://www.emacswiki.org/emacs/EmacsClient

firstarg=$1
case $firstarg in
    batch )
        shift
        if ! ps -ef | grep "emacs --daemon" | grep -v grep >> /dev/null; then
            emacs --daemon
            sleep 10
        fi ;;
    maximized )
        shift
        # check if the server is running, if not start the server
        if ! ps -ef | grep "emacs --daemon" | grep -v grep > /dev/null; then
            emacs --daemon
            exec emacsclient --alternate-editor="" --create-frame --eval "(make-frame '((name . \"maximized\") (top . 40) (left . 40) (width . 200) (height . 60)))" --eval "(select-frame-by-name \"maximized\")" "$@"
        else
            exec emacsclient --alternate-editor="" --eval "(make-frame '((name . \"maximized\") (top . 40) (left . 40) (width . 200) (height . 60)))" --eval "(select-frame-by-name \"maximized\")" "$@"
        fi
        ;;
    noframe )
        shift
        if ! ps -ef | grep "emacs --daemon" | grep -v grep >> /dev/null; then
            emacs --daemon
            exec emacsclient --alternate-editor="" -c "$@"
        else
            emacsclient --no-wait --eval "(if (> (length (frame-list)) 1) 't)" | grep t
            if [[ $? = "1" ]]; then
                emacsclient --create-frame --no-wait --alternate-editor="" "$@"
            else
                emacsclient --no-wait --alternate-editor="" "$@"
            fi
        fi
        ;;
    protocol )
        if ! ps -ef | grep "emacs --daemon" | grep -v grep >> /dev/null; then
            emacs --daemon
            exec emacsclient --create-frame --no-wait --alternate-editor="" -c "$@"
        else
            emacsclient --no-wait --eval "(if (> (length (frame-list)) 1) 't)" | grep t
            if [[ $? = "1" ]]; then
                emacsclient --create-frame --no-wait --alternate-editor="" "$@"
            else
                emacsclient --no-wait --alternate-editor="" "$@"
            fi
        fi
        ;;
    * )
        if ! ps -ef | grep "emacs --daemon" | grep -v grep >> /dev/null; then
            emacs --daemon
            exec emacsclient --alternate-editor="" --create-frame "$@"
        else
            exec emacsclient --alternate-editor="" --create-frame "$@"
        fi
        ;;
esac
# TODO: might want to make sure these work without server?
# TODO do I want to make zile, mg, or another terminal Emacs version the EDITOR?
# TODO possibly check display variable?
export EDITOR="launch-emacsclient -nw"
export ALTERNATE_EDITOR="launch-emacsclient -nw"
export VISUAL="launch-emacsclient -nw"
