#!/bin/bash
# launch-emacsclient launches an emacs client, optionally restarting
# the daemon with many options for frames and protocols and all that.
#
# Copyright (C) 2015-2019, Andrew Kroshko, all rights reserved.
#
# Author: Andrew Kroshko
# Maintainer: Andrew Kroshko <akroshko.public+devel@gmail.com>
# Created: Sun Sep 20, 2015
# Version: 20190228
# URL: https://github.com/akroshko/bash-stdlib
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

# check if the Emacs server is running, if not start the server
# see http://www.emacswiki.org/emacs/EmacsClient

# TODO: can remove some redundancy
firstarg=$1
# start emacs deamon if not already started
# XXXX: avoid starting daemon if computer is configured with systemd service
# TODO: better way to do this
if ! [[ -e "$HOME/.config/systemd/user/emacs.service" ]] && ! ps -ef | grep '[e]macs --daemon' >/dev/null; then
    emacs --daemon --no-init-file --load "$HOME/.emacs-cic.el"
    sleep 15
fi
# get emacsclient command based on nice value
if [[ $(ulimit -e) -gt "29" ]]; then
    EMACSCLIENT="nice --adjustment=-10 emacsclient"
else
    EMACSCLIENT="emacsclient"
fi
case $firstarg in
    batch )
        shift
        ;;
    capture )
        shift
        # check if the server is running, if not start the server
        # TODO: change name...
        if ! ps -ef | grep '[e]macs --daemon' >/dev/null; then
            $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame --eval "(make-frame '((name . \"capture\") (top . 40) (left . 40) (width . 200) (height . 60)))" --eval "(select-frame-by-name \"capture\")" "$@"
        else
            # TODO: why does this seem to be creating a frame anyways?
            exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"           --eval "(make-frame '((name . \"capture\") (top . 40) (left . 40) (width . 200) (height . 60)))" --eval "(select-frame-by-name \"capture\")" "$@"
        fi
        ;;
    # similar to capture but with different name, decide have "maximized" as frame name, decide if I really want to do this or if it's useful
    maximized )
        shift
        # check if the server is running, if not start the server
        if ! ps -ef | grep '[e]macs --daemon' >/dev/null; then
            exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame --eval "(make-frame '((name . \"*maximized*\") (top . 40) (left . 40) (width . 200) (height . 60) (user-position . t)))" --eval "(select-frame-by-name \"*maximized*\")" "$@"
        else
            # TODO: why does this seem to be creating a frame anyways?
            exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"                --eval "(make-frame '((name . \"*maximized*\") (top . 40) (left . 40) (width . 200) (height . 60) (user-position . t)))" --eval "(select-frame-by-name \"*maximized*\")" "$@"
        fi
        ;;

    # similar to capture but with different name, decide have "*transient*" as frame name, decide if I really want to do this?
    # TODO: figure out size from window
    # TODO: more custom names...
    transient )
        shift
        # check if the server is running, if not start the server
        if ! ps -ef | grep '[e]macs --daemon' >/dev/null; then
            exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame --eval "(make-frame '((name . \"*transient*\") (top . 40) (left . 40)   (width . 120) (height . 60) (user-position . t) (user-size . t)))" --eval "(select-frame-by-name \"*transient*\")" "$@"
        else
            # TODO: why does this seem to be creating a frame anyways?
            exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh"                --eval "(make-frame '((name . \"*transient*\") (top . 40) (left . 1320) (width . 120) (height . 60) (user-position . t) (user-size . t)))" --eval "(select-frame-by-name \"*transient*\")" "$@"
        fi
        ;;
    # no frame,
    noframe )
        shift
        if ! ps -ef | grep '[e]macs --daemon' >/dev/null; then
            $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" -c "$@"
        else
            emacsclient --no-wait --eval "(if (> (length (frame-list)) 1) 't)" | grep t
            if [[ $? = "1" ]]; then
                exec $EMACSCLIENT --create-frame --no-wait --alternate-editor="launch-emacsclient-fail.sh" "$@"
            else
                # TODO: why does this seem to be creating a frame anyways?
                exec $EMACSCLIENT                --no-wait --alternate-editor="launch-emacsclient-fail.sh" "$@"
            fi
        fi
        ;;
    protocol )
        shift
        if ! ps -ef | grep '[e]macs --daemon' >/dev/null; then
            $EMACSCLIENT --create-frame --no-wait --alternate-editor="launch-emacsclient-fail.sh" -c "$@"
        else
            emacsclient --no-wait --eval "(if (> (length (frame-list)) 1) 't)" | grep t
            if [[ $? = "1" ]]; then
                exec $EMACSCLIENT --create-frame --no-wait --alternate-editor="launch-emacsclient-fail.sh" "$@"
            else
                # TODO: why does this seem to be creating a frame anyways?
                exec $EMACSCLIENT                --no-wait --alternate-editor="launch-emacsclient-fail.sh" "$@"
            fi
        fi
        ;;
    nohup )
        shift
        # TODO: should nohup use exec?
        # TODO: things highlighted red, if I try to put this in a subshell, is this a real error?
        nohup $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame "$@" &>/dev/null &
        ;;
    sameframe )
        shift
        exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" "$@"
        ;;
    * )
        exec $EMACSCLIENT --alternate-editor="launch-emacsclient-fail.sh" --create-frame "$@"
        ;;
esac
# TODO: might want to make sure these work without server?
# TODO do I want to make zile, mg, or another terminal Emacs version the EDITOR?
# TODO possibly check display variable?
export EDITOR="launch-emacsclient -nw"
export ALTERNATE_EDITOR="launch-emacsclient -nw"
export VISUAL="launch-emacsclient -nw"
